import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  image: {
    width: 400,
    height: 300,
  },
  map: {
    flex: 7,
  },
  text: {
    flex: 1,
  },
  hanoverCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 130,
    top: 0,
  },
  bostonCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 110,
    top: 100,
  },
  nyCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 240,
    top: 190,
  },
  hanoverBigCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 160,
    top: 70,
  },
  lebanonCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 100,
    top: 130,
  },
  londonCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    top: 200,
  },
  loganCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 30,
    top: 110,
  },
  stationCircle: {
    width: 80,
    height: 80,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 230,
    top: 150,
  },
  next: {
    marginBottom: 100,
    width: 400,
    height: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextInactive: {
    marginBottom: 100,
    width: 400,
    height: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    backgroundColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nav: {
    width: 410,
    height: 100,
  },
  name: {
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 10,
    marginTop: 20,
  },
})

export default styles
